import streamlit as st

from .ui_helpers import render_json_card


def render_context_panel(report):
    """
    Context Inspector

    Canvas Intelligence Runtime Context
    """

    st.markdown("## Context Inspector")
    st.caption(
        "Inspect Canvas Runtime Context generated by the Intelligence Runtime."
    )

    context = report.context_snapshot

    tab_selected, tab_summary, tab_relationship = st.tabs(
        [
            "Selected Object",
            "Summary",
            "Relationships",
        ]
    )

    with tab_selected:
        diagnostics = context.get("selected_diagnostics", {})

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "Has Selection",
                "Yes" if diagnostics.get("has_selected_object") else "No",
            )

        with col2:
            st.metric(
                "Type",
                diagnostics.get("selected_type") or "-",
            )

        with col3:
            st.metric(
                "Payload",
                diagnostics.get("payload_type") or "-",
            )

        render_json_card(
            "Selected Object",
            context.get("selected_object"),
        )

    with tab_summary:
        diagnostics = context.get("summary_diagnostics", {})

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                "Keys",
                diagnostics.get("summary_key_count", 0),
            )

        with col2:
            st.metric(
                "Has Brief",
                "Yes" if diagnostics.get("has_brief") else "No",
            )

        with col3:
            st.metric(
                "Has Actions",
                "Yes" if diagnostics.get("has_actions") else "No",
            )

        render_json_card(
            "Canvas Intelligence Brief",
            context.get("summary"),
        )

    with tab_relationship:
        diagnostics = context.get("relationship_diagnostics", {})

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                "Relationships",
                diagnostics.get("relationship_count", 0),
            )

        with col2:
            st.metric(
                "Types",
                diagnostics.get("unique_relationship_types", 0),
            )

        render_json_card(
            "Relationship Types",
            diagnostics.get("relationship_types"),
        )

        render_json_card(
            "Relationships",
            context.get("relationships"),
        )